name: Publish to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Locate current version (or set to 0.0.0 if not found)
      id: version
      run: echo ::set-output name=VERSION::$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")

    - name: Log current version
      run: echo Current version is ${{ steps.version.outputs.VERSION }}

    - name: Increment minor version
      id: increment_version
      run: echo ::set-output name=VERSION::$(echo ${{ steps.version.outputs.VERSION }} | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')

    - name: Log new version
      run: echo New version is ${{ steps.increment_version.outputs.VERSION }}
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ steps.increment_version.outputs.VERSION }}

    - name: Update latest tag
      run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ steps.increment_version.outputs.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest